### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ManInMyVan** [ManInMyVan/Minecraft-Anticheat-List#7]
- [ ] Merge the "Edition" and "Platform" columns
- [ ] Merge the "Free" and "Premium" lists with a new column which will likely be labeled "Price"
- [ ] Finish marking some (most) of the "Unknown" column as "Old"
- [ ] Finish adding the rest of the anticheats to the site
- [ ] Add a new column to differentiate between full anticheats, addition anticheats, and others
- [ ] Rename the "Addon" platform to "Behavior Pack"
- [ ] Rename "NukkitX" to just "Nukkit"
- [ ] Fix the site on mobile
- [ ] Order the list better
